import { Risk, RiskDrvrList } from './risk.model';
import { AgentInfo } from './agent.model';
import { HEADER, PRODUCT_CAT } from '../../constants/motor-online-constants';

export class QUOTE_PROGRESS_MODEL {
    QuotationProgress: string;
    QuotationNumber: string;
    ClientIDType: string;
    ClientID: number;
    Risk: Risk;
    Gender: string;
    DOB: string;
    MaritalStatus: string;
    ProductCategory: string;
    RiskDrvrList: RiskDrvrList;
    ProductShortDescription: string;
    ProductCode: string;
    EffectiveDate: string;
    ExpiryDate: string;
    Agent!: {};
    AgentCode: string;
    CommAmt: string;
    GrossPremium: string;
    AnnualPremium: string;
    BasicPremium: string;
    STaxPct: string;
    STaxAmt: string;
    PolicySumInsured: string;
    PremiumDue: string;
    PremiumDueRounded: string;
    PremiumDueRoundedAfterPTV: string;
    RebateAmount: string;
    RebatePercentage: string;
    Stamp: string;
    PartnerCode: string;
    CNoteStatus: string;
    CNoteType: string;
    CommPercentage: string;
    IsEPolicy: string;
    MasterPolicyInd: string;
    PolSi: string;
    ProductType: string;
    CustomerAge: string;
    SourceSystem: string;
    SourceSystemCat: string;
    ClientName: string;
    MobileNumber: string;
    EmailAddress: string;
    Address_1: string;
    Address_2: string;
    Address_3: string;
    City: string;
    State: string;
    Country: string;
    PostCode: string;
    IsEuEea: string;
    ClientRefNo: string;
    ClientRefName: string;
    ClientRefPolicyNo: string;
    ReferralSalesStaffId: string;
    UTMMedium: string;
    UTMCampaign: string;
    MatchAgentMobile: string;
    MatchAgentEmail: string;
    Occupation?: string;
    OccupationCode?: string;
    CreatedDate?: string;
    IpAddress?: string;
    Voucher?: {};

    constructor(obj?: any) {
        this.QuotationProgress = obj && obj.QuotationProgress || '';
        this.QuotationNumber = obj && obj.QuotationNumber || '';
        this.ClientIDType = obj && obj.ClientIDType || '';
        this.ClientID = obj && obj.ClientID || '';
        this.ClientName = obj && obj.ClientName || '';
        this.MobileNumber = obj && obj.MobileNumber || '';
        this.EmailAddress = obj && obj.EmailAddress || '';
        this.Address_1 = obj && obj.Address_1 || '';
        this.Address_2 = obj && obj.Address_2 || '';
        this.Address_3 = obj && obj.Address_3 || '';
        this.City = obj && obj.City || '';
        this.State = obj && obj.State || '';
        this.Country = obj && obj.Country || '';
        this.PostCode = obj && obj.PostCode || '';
        this.DOB = obj && obj.DOB || '';
        this.Risk = obj && obj.Risk || new Risk();
        this.RiskDrvrList = obj && obj.RiskDrvrList || new RiskDrvrList();
        this.EffectiveDate = obj && obj.EffectiveDate || '';
        this.CommAmt = obj && obj.CommAmt || '';
        this.GrossPremium = obj && obj.GrossPremium || '';
        this.AnnualPremium = obj && obj.AnnualPremium || '';
        this.BasicPremium = obj && obj.BasicPremium || '';
        this.STaxPct = obj && obj.STaxPct || '';
        this.STaxAmt = obj && obj.STaxAmt || '';
        this.PolicySumInsured = obj && obj.PolicySumInsured || '';
        this.PremiumDueRounded = obj && obj.PremiumDueRounded || '';
        this.PremiumDueRoundedAfterPTV = obj && obj.PremiumDueRoundedAfterPTV || '';
        this.RebateAmount = obj && obj.RebateAmount || '';
        this.RebatePercentage = obj && obj.RebatePercentage || '';
        this.Stamp = obj && obj.Stamp || '';
        this.PartnerCode = obj && obj.PartnerCode || '';
        this.CNoteStatus = obj && obj.CNoteStatus || '';
        this.CNoteType = obj && obj.CNoteType || '';
        this.IsEPolicy = obj && obj.IsEPolicy || '';
        this.MasterPolicyInd = obj && obj.MasterPolicyInd || '';
        this.PolSi = obj && obj.PolSi || '';
        this.ProductType = obj && obj.ProductType || PRODUCT_CAT;
        this.CustomerAge = obj && obj.CustomerAge || null;
        this.Gender = obj && obj.Gender || '';
        this.MaritalStatus = obj && obj.MaritalStatus || '';
        this.ProductCategory = obj && obj.ProductCategory || PRODUCT_CAT;
        this.ProductShortDescription = obj && obj.ProductShortDescription || HEADER;
        this.ProductCode = obj && obj.ProductCode || '';
        this.ExpiryDate = obj && obj.ExpiryDate || '';
        this.Agent = obj && obj.Agent || new AgentInfo();
        this.AgentCode = obj && obj.AgentCode || '';
        this.PremiumDue = obj && obj.PremiumDue || '';
        this.CommPercentage = obj && obj.CommPercentage || '';
        this.SourceSystem = obj && obj.SourceSystem || '';
        this.SourceSystemCat = obj && obj.SourceSystemCat || '';
        this.IsEuEea = obj && obj.IsEuEea || '';
        this.ClientRefNo = obj && obj.ClientRefNo || '';
        this.ClientRefName = obj && obj.ClientRefName || '';
        this.ClientRefPolicyNo = obj && obj.ClientRefPolicyNo || '';
        this.ReferralSalesStaffId = obj && obj.ReferralSalesStaffId || '';
        this.UTMMedium = obj && obj.UTMMedium || '';
        this.UTMCampaign = obj && obj.UTMCampaign || '';
        this.MatchAgentMobile = obj && obj.MatchAgentMobile || '';
        this.MatchAgentEmail = obj && obj.MatchAgentEmail || '';
    }
}
