export const API_PATH = {
  VEHICLE_DETAILS: 'v1/openapi/mci/vehicleDetails',
  VALIDATE_VOUCHER: "/v1/openapi/uiservices/validateVoucher",
  AGENT_INFO: 'v1/openapi/mci/agentInfo',
  QUOTE_PROGRESS: 'v1/openapi/mci/quoteProgress',
  MAKE_LIST: 'v1/openapi/mci/makeList/W',
  REFERED_RISK_DETAILS: 'v1/openapi/mci/referRiskDetails/',
  PIAM: 'v1/openapi/mci/piam',
  MODEL_LIST: 'v1/openapi/mci/modelList',
  QUOTE: 'v1/openapi/mci/quote',
  CHECKUBB: 'v1/openapi/mci/checkUBB',
  MCI_CONTACT_AGENT: 'v1/openapi/mci/contactAgent',
  CHECK_SANCTION: 'v1/openapi/be/checkSanction',
  MO_QUALITY_CHECK: 'v1/openapi/qualityCheck',
  QUOTE_INFO: 'v1/openapi/mci/quoteInfo',
  IS_VALID_BIN_CARD_NUMBER: 'v1/openapi/uiservices/isValidBinCardNumber',
};
